In [16]:
# ============================================
# STEP 1: Import Required Libraries
# ============================================

# pandas → used for handling data (like Excel but more powerful)
import pandas as pd

# numpy → used for numerical operations
import numpy as np

# matplotlib → basic plotting (used later for EDA)
import matplotlib.pyplot as plt

# seaborn → advanced plotting (used later for better visuals)
import seaborn as sns

# plotly → interactive visualizations (used for dashboard later)
import plotly.express as px

In [17]:
# ============================================
# STEP 1: Load Cleaned IPC Dataset (2021)
# ============================================

# Load dataset
ipc_2021 = pd.read_excel("C:/Users/Varnika Sharma/Desktop/Crime Analysis/Crime Analysis/01_Data/Cleaned_Dataset/IPC_CRIMES/IPC_Crimes_Head-wise_Raw_2021.xlsx")

# Preview
ipc_2021.head()

,SL,State/UT,Offences affecting the Human Body_Murder (Sec.302 IPC)___I,Offences affecting the Human Body_Murder (Sec.302 IPC)___V,Offences affecting the Human Body_Murder (Sec.302 IPC)___R,Offences affecting the Human Body_Culpable Homicide not Amounting to Murder (Sec. 304 IPC)___I,Offences affecting the Human Body_Culpable Homicide not Amounting to Murder (Sec. 304 IPC)___V,Offences affecting the Human Body_Culpable Homicide not Amounting to Murder (Sec. 304 IPC)___R,Offences affecting the Human Body_Causing Death by Negligence_Deaths due to Negligence relating to Road Accidents_A) Hit and Run_I,Offences affecting the Human Body_Causing Death by Negligence_Deaths due to Negligence relating to Road Accidents_A) Hit and Run_V,...,Miscellaneous IPC Crimes_Circulate False/Fake News/Rumours (Sec.505 IPC/Sec.505 r/w IT Act)___R,Miscellaneous IPC Crimes_Criminal Intimidation (Sec.506 r/w Other IPC Crimes)___I,Miscellaneous IPC Crimes_Criminal Intimidation (Sec.506 r/w Other IPC Crimes)___V,Miscellaneous IPC Crimes_Criminal Intimidation (Sec.506 r/w Other IPC Crimes)___R,Miscellaneous IPC Crimes_Insult to the Modesty of Women (Sec.509 IPC)___I,Miscellaneous IPC Crimes_Insult to the Modesty of Women (Sec.509 IPC)___V,Miscellaneous IPC Crimes_Insult to the Modesty of Women (Sec.509 IPC)___R,Other IPC Crimes____I,Other IPC Crimes____V,Other IPC Crimes____R
0,1,Andhra Pradesh,956,985,1.8,112,134,0.2,739,761,...,0.1,2591,2631,4.9,2370,2384,9.0,27603,26679,52.2
1,2,Arunachal Pradesh,49,54,3.2,3,3,0.2,40,48,...,0.0,3,3,0.2,10,10,1.3,281,284,18.3
2,3,Assam,1192,1269,3.4,95,96,0.3,1475,1534,...,0.1,1538,1538,4.4,184,194,1.1,14805,14956,42.1
3,4,Bihar,2799,2826,2.3,136,140,0.1,1039,1097,...,0.1,319,319,0.3,1,1,0.0,200,187,0.2
4,5,Chhattisgarh,1007,1057,3.4,42,42,0.1,1777,1939,...,0.0,1989,1995,6.7,238,240,1.6,6273,6392,21.2

In [18]:
# Check shape
print(ipc_2021.shape)

# Check columns
ipc_2021.columns[:10]

(36, 358)

Index(['SL', 'State/UT',
       'Offences affecting the Human Body_Murder (Sec.302 IPC)___I',
       'Offences affecting the Human Body_Murder (Sec.302 IPC)___V',
       'Offences affecting the Human Body_Murder (Sec.302 IPC)___R',
       'Offences affecting the Human Body_Culpable Homicide not Amounting to Murder (Sec. 304 IPC)___I',
       'Offences affecting the Human Body_Culpable Homicide not Amounting to Murder (Sec. 304 IPC)___V',
       'Offences affecting the Human Body_Culpable Homicide not Amounting to Murder (Sec. 304 IPC)___R',
       'Offences affecting the Human Body_Causing Death by Negligence_Deaths due to Negligence relating to Road Accidents_A) Hit and Run_I',
       'Offences affecting the Human Body_Causing Death by Negligence_Deaths due to Negligence relating to Road Accidents_A) Hit and Run_V'],
      dtype='str')

In [19]:
# Drop unnecessary column
ipc_2021.drop(columns=["SL"], inplace=True)

ipc_2021.head()

,State/UT,Offences affecting the Human Body_Murder (Sec.302 IPC)___I,Offences affecting the Human Body_Murder (Sec.302 IPC)___V,Offences affecting the Human Body_Murder (Sec.302 IPC)___R,Offences affecting the Human Body_Culpable Homicide not Amounting to Murder (Sec. 304 IPC)___I,Offences affecting the Human Body_Culpable Homicide not Amounting to Murder (Sec. 304 IPC)___V,Offences affecting the Human Body_Culpable Homicide not Amounting to Murder (Sec. 304 IPC)___R,Offences affecting the Human Body_Causing Death by Negligence_Deaths due to Negligence relating to Road Accidents_A) Hit and Run_I,Offences affecting the Human Body_Causing Death by Negligence_Deaths due to Negligence relating to Road Accidents_A) Hit and Run_V,Offences affecting the Human Body_Causing Death by Negligence_Deaths due to Negligence relating to Road Accidents_A) Hit and Run_R,...,Miscellaneous IPC Crimes_Circulate False/Fake News/Rumours (Sec.505 IPC/Sec.505 r/w IT Act)___R,Miscellaneous IPC Crimes_Criminal Intimidation (Sec.506 r/w Other IPC Crimes)___I,Miscellaneous IPC Crimes_Criminal Intimidation (Sec.506 r/w Other IPC Crimes)___V,Miscellaneous IPC Crimes_Criminal Intimidation (Sec.506 r/w Other IPC Crimes)___R,Miscellaneous IPC Crimes_Insult to the Modesty of Women (Sec.509 IPC)___I,Miscellaneous IPC Crimes_Insult to the Modesty of Women (Sec.509 IPC)___V,Miscellaneous IPC Crimes_Insult to the Modesty of Women (Sec.509 IPC)___R,Other IPC Crimes____I,Other IPC Crimes____V,Other IPC Crimes____R
0,Andhra Pradesh,956,985,1.8,112,134,0.2,739,761,1.4,...,0.1,2591,2631,4.9,2370,2384,9.0,27603,26679,52.2
1,Arunachal Pradesh,49,54,3.2,3,3,0.2,40,48,2.6,...,0.0,3,3,0.2,10,10,1.3,281,284,18.3
2,Assam,1192,1269,3.4,95,96,0.3,1475,1534,4.2,...,0.1,1538,1538,4.4,184,194,1.1,14805,14956,42.1
3,Bihar,2799,2826,2.3,136,140,0.1,1039,1097,0.8,...,0.1,319,319,0.3,1,1,0.0,200,187,0.2
4,Chhattisgarh,1007,1057,3.4,42,42,0.1,1777,1939,6.0,...,0.0,1989,1995,6.7,238,240,1.6,6273,6392,21.2

In [20]:
ipc_2021.rename(columns={"State/UT": "State"}, inplace=True)