In [1]:
#!pip install hvplot 
#!pip install panel

In [2]:
import pandas as pd
import numpy as np
import panel as pn
pn.extension('tabulator')

import hvplot.pandas

In [3]:
df = pd.read_csv("owid-co2-data.csv")

In [4]:
# cache data to improve dashboard performance
if 'data' not in pn.state.cache.keys():

    df = pd.read_csv('owid-co2-data.csv')

    pn.state.cache['data'] = df.copy()

else: 

    df = pn.state.cache['data']

In [5]:
df

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560.0,NaN,0.000,0.000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50406,Zimbabwe,2020,ZWE,15526887.0,2.317871e+10,0.496,0.032,8.491,-1.776,-17.298,...,NaN,0.106,0.001,0.001,0.002,0.0,24.146,14.463,1.991,23.450
50407,Zimbabwe,2021,ZWE,15797220.0,2.514009e+10,0.542,0.034,10.223,1.732,20.398,...,NaN,0.105,0.001,0.001,0.002,0.0,27.907,16.408,2.137,20.899
50408,Zimbabwe,2022,ZWE,16069061.0,2.590159e+10,0.387,0.024,12.232,2.009,19.653,...,NaN,0.104,0.001,0.001,0.002,0.0,29.917,18.830,1.380,11.283
50409,Zimbabwe,2023,ZWE,16340829.0,NaN,0.387,0.024,13.443,1.211,9.904,...,NaN,0.103,0.001,0.001,0.002,0.0,31.029,20.318,1.876,13.957
50410,Zimbabwe,2024,ZWE,16634366.0,NaN,0.387,0.023,13.701,0.258,1.918,...,NaN,0.102,0.001,0.001,0.002,0.0,31.066,20.773,NaN,NaN

In [6]:
df[df['country'] == 'North America']

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
33561,North America,1750,NaN,11430595.0,NaN,0.000,0.000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33562,North America,1751,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33563,North America,1752,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33564,North America,1753,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33565,North America,1754,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33831,North America,2020,NaN,598250669.0,NaN,72.889,0.123,5798.350,-665.012,-10.289,...,30.780,22.842,0.052,0.295,0.361,0.014,7516.451,6646.829,453.481,7.821
33832,North America,2021,NaN,600876349.0,NaN,75.463,0.126,6176.852,378.502,6.528,...,32.361,22.709,0.053,0.297,0.364,0.014,7916.797,7065.010,527.933,8.547
33833,North America,2022,NaN,604356255.0,NaN,74.810,0.125,6236.024,59.172,0.958,...,31.419,22.574,0.053,0.300,0.368,0.014,7991.777,7146.622,570.639,9.151
33834,North America,2023,NaN,608770547.0,NaN,73.740,0.122,6104.681,-131.343,-2.106,...,32.366,22.440,0.053,0.303,0.371,0.015,7890.547,7036.821,571.560,9.363
33835,North America,2024,NaN,613150315.0,NaN,70.584,0.116,6084.276,-20.404,-0.334,...,32.411,22.308,0.054,0.306,0.374,0.015,7849.071,7015.351,NaN,NaN

In [7]:
df[df['country'] == 'World']

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
49511,World,1750,NaN,7.532793e+08,NaN,NaN,NaN,9.306,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49512,World,1751,NaN,NaN,NaN,NaN,NaN,9.407,0.101,1.088,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49513,World,1752,NaN,NaN,NaN,NaN,NaN,9.505,0.098,1.041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49514,World,1753,NaN,NaN,NaN,NaN,NaN,9.610,0.105,1.108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49515,World,1754,NaN,NaN,NaN,NaN,NaN,9.734,0.123,1.281,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49781,World,2020,NaN,7.887001e+09,1.185900e+14,1624.052,0.206,35158.230,-1928.339,-5.200,...,100.0,100.0,0.359,1.142,1.581,0.080,50601.266,40091.508,0.0,0.0
49782,World,2021,NaN,7.954448e+09,1.260048e+14,1666.885,0.210,36866.863,1708.634,4.860,...,100.0,100.0,0.363,1.160,1.605,0.082,52639.844,41943.742,0.0,0.0
49783,World,2022,NaN,8.021407e+09,1.301126e+14,1578.739,0.197,37527.773,660.910,1.793,...,100.0,100.0,0.368,1.179,1.629,0.083,53515.586,42687.125,0.0,0.0
49784,World,2023,NaN,8.091735e+09,NaN,1540.286,0.190,38094.039,566.268,1.509,...,100.0,100.0,0.372,1.197,1.654,0.084,54092.184,43274.887,0.0,0.0
49785,World,2024,NaN,8.161973e+09,NaN,1472.818,0.180,38598.578,504.537,1.324,...,100.0,100.0,0.377,1.216,1.678,0.085,54433.398,43714.777,0.0,0.0

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50411 entries, 0 to 50410
Data columns (total 79 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country                                    50411 non-null  str
 1   year                                       50411 non-null  int64
 2   iso_code                                   42480 non-null  str
 3   population                                 41167 non-null  float64
 4   gdp                                        15251 non-null  float64
 5   cement_co2                                 29173 non-null  float64
 6   cement_co2_per_capita                      25648 non-null  float64
 7   co2                                        29384 non-null  float64
 8   co2_growth_abs                             27216 non-null  float64
 9   co2_growth_prct                            26239 non-null  float64
 10  co2_including_luc                          23796 non-null  float64
 11  co2_including_luc_growth_abs               23496 non-null  float64
 12  co2_including_luc_growth_prct              23496 non-null  float64
 13  co2_including_luc_per_capita               23757 non-null  float64
 14  co2_including_luc_per_gdp                  16790 non-null  float64
 15  co2_including_luc_per_unit_energy          10020 non-null  float64
 16  co2_per_capita                             26509 non-null  float64
 17  co2_per_gdp                                17528 non-null  float64
 18  co2_per_unit_energy                        10699 non-null  float64
 19  coal_co2                                   21925 non-null  float64
 20  coal_co2_per_capita                        21314 non-null  float64
 21  consumption_co2                            5053 non-null   float64
 22  consumption_co2_per_capita                 4643 non-null   float64
 23  consumption_co2_per_gdp                    4448 non-null   float64
 24  cumulative_cement_co2                      29151 non-null  float64
 25  cumulative_co2                             27563 non-null  float64
 26  cumulative_co2_including_luc               23796 non-null  float64
 27  cumulative_coal_co2                        21925 non-null  float64
 28  cumulative_flaring_co2                     16111 non-null  float64
 29  cumulative_gas_co2                         18147 non-null  float64
 30  cumulative_luc_co2                         37450 non-null  float64
 31  cumulative_oil_co2                         25458 non-null  float64
 32  cumulative_other_co2                       3254 non-null   float64
 33  energy_per_capita                          10459 non-null  float64
 34  energy_per_gdp                             7787 non-null   float64
 35  flaring_co2                                16174 non-null  float64
 36  flaring_co2_per_capita                     14910 non-null  float64
 37  gas_co2                                    18147 non-null  float64
 38  gas_co2_per_capita                         17446 non-null  float64
 39  ghg_excluding_lucf_per_capita              35842 non-null  float64
 40  ghg_per_capita                             36179 non-null  float64
 41  land_use_change_co2                        37450 non-null  float64
 42  land_use_change_co2_per_capita             36635 non-null  float64
 43  methane                                    38150 non-null  float64
 44  methane_per_capita                         36179 non-null  float64
 45  nitrous_oxide                              38500 non-null  float64
 46  nitrous_oxide_per_capita                   36439 non-null  float64
 47  oil_co2                                    25459 non-null  float64
 48  oil_co2_per_capita                         24722 non-null  float64
 49  other_co2_per_capita                       2659 non-null   float64
 50  other_industry_co2                         3254 non-null   float64
 51  primary_energy_consumption                 10503 non-null  float64
 52  share_global_cement_co2                    22270 non-null  float64
 53  share_global_co2                           27563 non-null  float64
 54  share_global_co2_including_luc             23796 non-null  float64
 55  share_global_coal_co2                      21925 non-null  float64
 56  share_global_cumulative_cement_co2         22270 non-null  float64
 57  share_global_cumulative_co2                27563 non-null  float64
 58  share_global_cumulative_co2_including_luc  23796 non-null  float64
 59  share_global_cumulative_coal_co2           21925 non-null  float64
 60  share_global_cumulative_flaring_co2        11089 non-null  float64
 61  share_global_cumulative_gas_co2            15167 non-null  float64
 62  share_global_cumulative_luc_co2            37450 non-null  float64
 63  share_global_cumulative_oil_co2            23833 non-null  float64
 64  share_global_cumulative_other_co2          2170 non-null   float64
 65  share_global_flaring_co2                   11089 non-null  float64
 66  share_global_gas_co2                       15167 non-null  float64
 67  share_global_luc_co2                       37450 non-null  float64
 68  share_global_oil_co2                       23833 non-null  float64
 69  share_global_other_co2                     2170 non-null   float64
 70  share_of_temperature_change_from_ghg       41238 non-null  float64
 71  temperature_change_from_ch4                38280 non-null  float64
 72  temperature_change_from_co2                41238 non-null  float64
 73  temperature_change_from_ghg                41238 non-null  float64
 74  temperature_change_from_n2o                38280 non-null  float64
 75  total_ghg                                  38150 non-null  float64
 76  total_ghg_excluding_lucf                   37813 non-null  float64
 77  trade_co2                                  4712 non-null   float64
 78  trade_co2_share                            4712 non-null   float64
dtypes: float64(76), int64(1), str(2)
memory usage: 30.4 MB

In [9]:
df.isnull().sum()

country                            0
year                               0
iso_code                        7931
population                      9244
gdp                            35160
                               ...
temperature_change_from_n2o    12131
total_ghg                      12261
total_ghg_excluding_lucf       12598
trade_co2                      45699
trade_co2_share                45699
Length: 79, dtype: int64

## (0) Some minor data preprocessing

In [10]:
# Fill NAs with 0s and create GDP per capita column
df = df.fillna(0)
df['gdp_per_capita'] = np.where(df['population']!= 0, df['gdp']/ df['population'], 0)

In [11]:
df

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share,gdp_per_capita
0,Afghanistan,1750,AFG,2802560.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000000
1,Afghanistan,1751,AFG,0.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000000
2,Afghanistan,1752,AFG,0.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000000
3,Afghanistan,1753,AFG,0.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000000
4,Afghanistan,1754,AFG,0.0,0.000000e+00,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50406,Zimbabwe,2020,ZWE,15526887.0,2.317871e+10,0.496,0.032,8.491,-1.776,-17.298,...,0.106,0.001,0.001,0.002,0.0,24.146,14.463,1.991,23.450,1492.810966
50407,Zimbabwe,2021,ZWE,15797220.0,2.514009e+10,0.542,0.034,10.223,1.732,20.398,...,0.105,0.001,0.001,0.002,0.0,27.907,16.408,2.137,20.899,1591.424869
50408,Zimbabwe,2022,ZWE,16069061.0,2.590159e+10,0.387,0.024,12.232,2.009,19.653,...,0.104,0.001,0.001,0.002,0.0,29.917,18.830,1.380,11.283,1611.891689
50409,Zimbabwe,2023,ZWE,16340829.0,0.000000e+00,0.387,0.024,13.443,1.211,9.904,...,0.103,0.001,0.001,0.002,0.0,31.029,20.318,1.876,13.957,0.000000
50410,Zimbabwe,2024,ZWE,16634366.0,0.000000e+00,0.387,0.023,13.701,0.258,1.918,...,0.102,0.001,0.001,0.002,0.0,31.066,20.773,0.000,0.000,0.000000

In [12]:
# Make DataFrame Pipeline Interactive
idf = df.interactive()

## (1) CO2 emission over time by continent

In [13]:
# Define Panel widgets
year_slider = pn.widgets.IntSlider(name='Year slider', start=1850, end=2026, step=5,value=1850)
year_slider

IntSlider(end=2026, name='Year slider', start=1850, step=5, value=1850)

In [14]:
# Radio buttons for CO2 measures
yaxis_co2 = pn.widgets.RadioButtonGroup(
    name='Y axis', 
    options=['co2', 'co2_per_capita',],
    button_type='success'
)
yaxis_co2

RadioButtonGroup(button_type='success', name='Y axis', options=['co2', 'co2_per_capita'], value='co2')

In [15]:
continents = ['World', 'Asia', 'Oceania', 'Europe', 'Africa', 'North America', 
              'South America', 'Antarctica']
co2_pipeline = (
    idf[
        (idf.year <= year_slider) &
        (idf.country.isin(continents))
    ]
    .groupby(['country', 'year'])[yaxis_co2].mean()
    .to_frame()
    .reset_index()
    .sort_values(by='year')  
    .reset_index(drop=True)
)

In [16]:
co2_pipeline

In [17]:
co2_plot = co2_pipeline.hvplot(x = 'year', by='country', 
                               y=yaxis_co2,
                               line_width=2, 
                               title="CO2 emission by continent")
co2_plot

## (2) Table - CO2 emission over time by continent

In [18]:
co2_table = co2_pipeline.pipe(pn.widgets.Tabulator, pagination='remote', page_size = 10, sizing_mode='stretch_width') 
co2_table

## (3) CO2 vs GDP scatterplot

In [19]:
co2_vs_gdp_scatterplot_pipeline = (
    idf[
        (idf.year == year_slider) &
        (~ (idf.country.isin(continents)))
    ]
    .groupby(['country', 'year', 'gdp_per_capita'])['co2'].mean()
    .to_frame()
    .reset_index()
    .sort_values(by='year')  
    .reset_index(drop=True)
)

In [20]:
co2_vs_gdp_scatterplot_pipeline

In [21]:
co2_vs_gdp_scatterplot = co2_vs_gdp_scatterplot_pipeline.hvplot(x='gdp_per_capita',y='co2', 
                        by='country',size=80, kind="scatter", alpha=0.7,
                       legend=False,height=500, width=500)
co2_vs_gdp_scatterplot

## (4) Bar chart with CO2 sources by continent

In [22]:
yaxis_co2_source = pn.widgets.RadioButtonGroup(
    name='Y axis', 
    options=['coal_co2', 'oil_co2', 'gas_co2'], 
    button_type='success'
)

continents_excl_world = ['Asia', 'Oceania', 'Europe', 'Africa', 'North America', 'South America', 'Antarctica']

co2_source_bar_pipeline = (
    idf[
        (idf.year == year_slider) &
        (idf.country.isin(continents_excl_world))
    ]
    .groupby(['year', 'country'])[yaxis_co2_source].sum()
    .to_frame()
    .reset_index()
    .sort_values(by='year')  
    .reset_index(drop=True)
)

In [23]:
co2_source_bar_plot = co2_source_bar_pipeline.hvplot(kind='bar', 
                        x='country',y=yaxis_co2_source, 
                        title='CO2 source by continent')
co2_source_bar_plot

## Creating Dashboard

In [25]:
#12  17 18 23 31 44 47 52 


#Layout using Template
template = pn.template.FastListTemplate(
    title='World CO2 emission dashboard', 
    sidebar=[pn.pane.Markdown("# CO2 Emissions and Climate Change"), 
             pn.pane.Markdown("#### Carbon dioxide "), 
             pn.pane.PNG('climate_day.png', sizing_mode='scale_both'),
             pn.pane.Markdown("## Settings"),   
             year_slider],
    main=[pn.Row(pn.Column(yaxis_co2, 
                co2_plot.panel(width=700), margin=(0,25)), 
                co2_table.panel(width=500)), 
          pn.Row(pn.Column(co2_vs_gdp_scatterplot.panel(width=600), margin=(0,25)), pn.Column(yaxis_co2_source, co2_source_bar_plot.panel(width=600)))],
    accent_base_color="#88d8b0",
    header_background="#88d8b0",
)
template.show()
template.servable();

Launching server at http://localhost:59236

WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='9f77e0bf-6a6c-4feb-a75a-d367a53fa37e', ...)
WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='6c6c31b0-8450-4fbb-80a6-4486b6737359', ...)
WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='af64c191-79cd-4aeb-998a-7bbb7ef618f6', ...)

2026-04-23 00:44:52,037 ERROR: panel.reactive - Callback failed for object named 'Y axis' changing property {'value': 'co2_per_capita'}
Traceback (most recent call last):
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\reactive.py", line 479, in _process_events
    self.param.update(**self_params)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 2788, in update
    restore = dict(self_._update(arg, **kwargs))
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 2821, in _update
    self_._batch_call_watchers()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 3038, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 3000, in _execute_watcher
    watcher.fn(*args, **kwargs)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\param.py", line 956, in _replace_pane
    self._update_inner(new_object)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\pane\base.py", line 777, in _update_inner
    self._inner_layout[:] = [self._pane]
    ~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\layout\base.py", line 412, in __setitem__
    self.objects = new_objects
    ^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 629, in _f
    instance_param.__set__(obj, val)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 631, in _f
    return f(self, obj, val)
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\viewable.py", line 1206, in __set__
    super().__set__(obj, self._transform_value(val))
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 631, in _f
    return f(self, obj, val)
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 1879, in __set__
    obj.param._call_watcher(watcher, event)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 3018, in _call_watcher
    self_._execute_watcher(watcher, (event,))
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 3000, in _execute_watcher
    watcher.fn(*args, **kwargs)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\reactive.py", line 463, in _param_change
    self._apply_update(named_events, properties, model, ref)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\reactive.py", line 351, in _apply_update
    self._update_model(events, msg, root, model, doc, comm)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\layout\base.py", line 257, in _update_model
    with freeze_doc(doc, model, msg, force=update_children):
         ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\io\document.py", line 660, in freeze_doc
    doc.models._pop_freeze()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\bokeh\document\models.py", line 288, in _pop_freeze
    self.recompute()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\bokeh\document\models.py", line 235, in recompute
    ma._attach_document(document)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\bokeh\model\model.py", line 600, in _attach_document
    raise RuntimeError(f"Models must be owned by only a single document, {self!r} is already in a doc")
RuntimeError: Models must be owned by only a single document, ImportedStyleSheet(id='af4d0d35-11c5-4b33-a067-1f2212ccae7b', ...) is already in a doc
2026-04-23 00:44:53,815 ERROR: panel.reactive - Callback failed for object named 'Y axis' changing property {'value': 'co2'}
Traceback (most recent call last):
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\reactive.py", line 479, in _process_events
    self.param.update(**self_params)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 2788, in update
    restore = dict(self_._update(arg, **kwargs))
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 2821, in _update
    self_._batch_call_watchers()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 3038, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 3000, in _execute_watcher
    watcher.fn(*args, **kwargs)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\param.py", line 956, in _replace_pane
    self._update_inner(new_object)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\pane\base.py", line 777, in _update_inner
    self._inner_layout[:] = [self._pane]
    ~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\layout\base.py", line 412, in __setitem__
    self.objects = new_objects
    ^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 629, in _f
    instance_param.__set__(obj, val)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 631, in _f
    return f(self, obj, val)
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\viewable.py", line 1206, in __set__
    super().__set__(obj, self._transform_value(val))
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 631, in _f
    return f(self, obj, val)
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 1879, in __set__
    obj.param._call_watcher(watcher, event)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 3018, in _call_watcher
    self_._execute_watcher(watcher, (event,))
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\param\parameterized.py", line 3000, in _execute_watcher
    watcher.fn(*args, **kwargs)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\reactive.py", line 463, in _param_change
    self._apply_update(named_events, properties, model, ref)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\reactive.py", line 351, in _apply_update
    self._update_model(events, msg, root, model, doc, comm)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\layout\base.py", line 257, in _update_model
    with freeze_doc(doc, model, msg, force=update_children):
         ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\contextlib.py", line 148, in __exit__
    next(self.gen)
    ~~~~^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\panel\io\document.py", line 660, in freeze_doc
    doc.models._pop_freeze()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\bokeh\document\models.py", line 288, in _pop_freeze
    self.recompute()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\bokeh\document\models.py", line 235, in recompute
    ma._attach_document(document)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Varnika Sharma\AppData\Local\Programs\Python\Python314\Lib\site-packages\bokeh\model\model.py", line 600, in _attach_document
    raise RuntimeError(f"Models must be owned by only a single document, {self!r} is already in a doc")
RuntimeError: Models must be owned by only a single document, ImportedStyleSheet(id='af4d0d35-11c5-4b33-a067-1f2212ccae7b', ...) is already in a doc

WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='7a50df60-67ba-4167-a61b-b3212e607915', ...)
WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='b365f954-2e7e-486a-b019-47b28b0666ea', ...)
WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='2c1b13ea-1d36-4418-8b6d-695834b74bbd', ...)
WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='5540e69e-f696-41a4-9a66-f73dbc4bf8ad', ...)